language: ruby

script: bundle exec rspec

rvm:
  - "1.9.3"
  - "2.0.0"
  - jruby-19mode

env:
  - "RAILS_VERSION=3.0.7"
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=master"

matrix:
  allow_failures:
    - env: "RAILS_VERSION=3.0.7"
      rvm: 2.0.0
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
